#!/bin/bash
# End-to-end OTA verification in a VM, against the LIVE update server.
#
#   release/verify-vm-update.sh [path-to-ota-test-image.bin]
#
# Boots the OTA-test image (chromium/build-ota-test-image.sh) in a crosvm
# instance, installs it onto a second disk with chromeos-install (the raw
# .bin has a 2 MiB ROOT-B; only an installed disk can take an update),
# reboots from that disk in OFFICIAL mode (no cros_debug on the kernel
# cmdline, so debug_build=0 and update_engine enforces payload signatures
# against the baked pubkey), and then:
#
#   - if the live server has nothing newer than the image's version, the
#     run asserts that a check yields "noupdate" and stops: that is the
#     correct baseline result for a device already on the latest release.
#   - if the server offers a newer version, the run drives
#     update_engine_client --check_for_update, polls --status to
#     UPDATE_STATUS_UPDATED_NEED_REBOOT, checks the GPT slot switch,
#     reboots into the new slot and asserts the booted system reports the
#     new CHROMEOS_RELEASE_VERSION (via cgpt boot-success attributes and
#     debugfs, because the updated rootfs is a real release rootfs with no
#     SSH).
#
# Test-only deviations from a real device, all boot-path not update-path:
#   - direct-kernel boot (crosvm has no vboot firmware), so the slot
#     switch is enacted by us reading the GPT attributes that postinst
#     wrote rather than by firmware; dm-verity of the new rootfs is
#     regenerated by postinst but not enforced on the next boot.
#   - the new slot is booted with the release build's vmlinuz from the
#     host (CROS_VM_KERNEL), matching what KERN-B contains.
#   - OOBE is marked complete by touching /home/chronos/.oobe_completed:
#     the server response carries no deadline, and update_engine refuses
#     non-critical updates while OOBE is incomplete
#     (kNonCriticalUpdateInOOBE). Real devices complete OOBE for real.
#
# Requires: a built OTA-test image, tools/vm-instance.sh, and (for the
# update leg) a signed+published newer release.
set -eu
DEVENV="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$DEVENV"
BOARD="${BOARD:-colorburst}"
OMAHA="https://update.colorburst.net/update"
APPID="{3EFFC3C6-5828-4F3A-967D-BAEA412E2DC8}"

# --- image ------------------------------------------------------------
if [ $# -ge 1 ]; then
    IMG="$(readlink -f "$1")"
else
    IMG="$(ls -t chromiumos/src/build/images/${BOARD}/*/colorburst-*-ota-test.bin 2>/dev/null | head -1)"
fi
[ -n "${IMG:-}" ] && [ -f "$IMG" ] || {
    echo "no OTA-test image -- run chromium/build-ota-test-image.sh first" >&2
    exit 1
}
BASE_VER="$(basename "$IMG" | sed 's/^colorburst-\(.*\)-ota-test\.bin$/\1/')"
echo "== OTA-test image: $IMG (version ${BASE_VER})"

# The kernel for the post-update boot: the newest release build's.
NEW_KERNEL_DEFAULT="$(ls -t chromiumos/src/build/images/${BOARD}/*/boot_images/vmlinuz 2>/dev/null | head -1)"
NEW_KERNEL="${NEW_KERNEL:-$NEW_KERNEL_DEFAULT}"

# --- what does the live server say? -----------------------------------
probe_server() { # probe_server <version> -> "noupdate" | offered version
    local resp
    resp="$(curl -sS --max-time 30 -X POST --data-binary @- "$OMAHA" <<EOF
<request protocol="3.0"><app appid="${APPID}" version="$1" track="stable-channel" board="${BOARD}" delta_okay="false"><updatecheck></updatecheck></app></request>
EOF
)"
    if echo "$resp" | grep -q 'updatecheck status="noupdate"'; then
        echo noupdate
    else
        echo "$resp" | sed -n 's/.*<manifest version="\([^"]*\)".*/\1/p'
    fi
}
OFFER="$(probe_server "$BASE_VER")"
if [ "$OFFER" = noupdate ]; then
    echo "== live server: noupdate for ${BASE_VER} (device is current)"
    EXPECT=baseline
else
    echo "== live server offers ${OFFER} to a ${BASE_VER} device"
    EXPECT="$OFFER"
    [ -n "$NEW_KERNEL" ] || { echo "no release vmlinuz found for the post-update boot" >&2; exit 1; }
fi

# --- VM plumbing ------------------------------------------------------
VMTOOL=tools/vm-instance.sh
ID="${OTA_VM_ID:-}"
if [ -z "$ID" ]; then
    ID="$($VMTOOL alloc verify-ota | sed -n 's/^instance \([0-9]*\) allocated.*/\1/p')"
    [ -n "$ID" ] || { echo "could not allocate a VM instance" >&2; exit 1; }
    echo "== allocated VM instance $ID (release with: $VMTOOL release $ID)"
fi
WORK="chromiumos/.vm/$ID"
TARGET="$WORK/ota-target.img"
TARGET_SDK="/mnt/host/source/.vm/$ID/ota-target.img"

vm_running() { docker ps --format '{{.Names}}' | grep -qx "cros-vm-$ID"; }
vm_boot() { # vm_boot <extra env...>
    ( cd "$DEVENV" && env CROS_VM_ID="$ID" CROS_VM_MEM=8192 CROS_VM_SCSI=1 \
        CROS_VM_IMAGE="$IMG" CROS_VM_DISK2=ota-target.img \
        CROS_VM_DISK2_SIZE=16G "$@" \
        nohup ./run-crosvm.sh > "$WORK/boot.log" 2>&1 & )
}
vm_ssh() { $VMTOOL ssh "$ID" "$@"; }
wait_ssh() {
    local i
    for i in $(seq 1 60); do
        vm_ssh true 2>/dev/null && return 0
        sleep 5
    done
    echo "VM $ID did not become reachable over SSH" >&2
    tail -20 "$WORK/console.log" 2>/dev/null >&2 || true
    return 1
}
wait_stopped() {
    local i
    for i in $(seq 1 60); do vm_running || return 0; sleep 2; done
    docker kill "cros-vm-$ID" >/dev/null 2>&1 || true
}
run_sdk() { ./cros-sdk.sh cros_sdk -- "$@"; }

if vm_running; then
    echo "instance $ID already running -- stop it first ($VMTOOL stop $ID)" >&2
    exit 1
fi

# --- phase 1: install onto the second disk ----------------------------
if [ -f "$WORK/.ota-installed" ]; then
    echo "== phase 1: $TARGET already installed (rm $WORK/.ota-installed to redo)"
else
    echo "== phase 1: booting the raw image to run chromeos-install onto /dev/sdb"
    rm -f "$TARGET"
    vm_boot
    wait_ssh
    echo "   installing (a few minutes)..."
    vm_ssh 'chromeos-install --dst /dev/sdb --yes' >"$WORK/install.log" 2>&1 || {
        echo "chromeos-install failed; see $WORK/install.log" >&2; exit 1
    }
    vm_ssh 'poweroff' 2>/dev/null || true
    wait_stopped
    touch "$WORK/.ota-installed"
    echo "   installed."
fi

# --- phase 2: official boot from the installed disk -------------------
echo "== phase 2: booting the INSTALLED system, official mode (no cros_debug)"
vm_boot CROS_VM_BOOT_DISK2=1 CROS_VM_OFFICIAL=1
wait_ssh

echo "-- sanity: officialness and configuration"
vm_ssh 'crossystem debug_build; echo "debug_build rc=$?"' || true
vm_ssh 'rootdev -s; grep -E "AUSERVER|RELEASE_VERSION|RELEASE_TRACK|APPID" /etc/lsb-release'
vm_ssh 'ls -l /usr/share/update_engine/update-payload-key.pub.pem'
# OOBE gate: without a deadline in the response, update_engine refuses
# updates while OOBE is incomplete.
vm_ssh '[ -f /home/chronos/.oobe_completed ] || { touch /home/chronos/.oobe_completed; restart update-engine || true; sleep 3; }'
vm_ssh 'update_engine_client --status' || true
if vm_ssh 'grep -q "Unofficial build, blocking" /var/log/update_engine.log' 2>/dev/null; then
    echo "FAIL: update_engine still thinks this is an unofficial build" >&2
    exit 1
fi
echo "OK   update_engine does not report an unofficial build"

echo "-- triggering an update check against $OMAHA"
vm_ssh 'update_engine_client --check_for_update'

if [ "$EXPECT" = baseline ]; then
    sleep 20
    STATUS="$(vm_ssh 'update_engine_client --status' 2>/dev/null || true)"
    echo "$STATUS" | sed 's/^/    /'
    vm_ssh 'tail -40 /var/log/update_engine.log' | sed 's/^/    /'
    echo "$STATUS" | grep -q 'UPDATE_STATUS_IDLE' &&
        vm_ssh 'grep -q "no update" /var/log/update_engine.log || grep -qi noupdate /var/log/update_engine.log' && {
        echo; echo "=== BASELINE VERIFIED: official-mode device on ${BASE_VER} reached ${OMAHA} and was told noupdate ==="
        echo "(re-run after signing+publishing a newer release to see a real update)"
        vm_ssh 'poweroff' 2>/dev/null || true; wait_stopped
        exit 0
    }
    echo "=== BASELINE FAILED: expected a clean noupdate; see log above ===" >&2
    exit 1
fi

echo "-- polling for UPDATE_STATUS_UPDATED_NEED_REBOOT (payload ~650MB)"
START=$(date +%s)
DEADLINE=$(( START + 2400 ))
while :; do
    STATUS="$(vm_ssh 'update_engine_client --status' 2>/dev/null || true)"
    OP="$(echo "$STATUS" | sed -n 's/^CURRENT_OP=//p')"
    PROG="$(echo "$STATUS" | sed -n 's/^PROGRESS=//p')"
    echo "   $(date +%H:%M:%S) $OP $PROG"
    case "$OP" in
        UPDATE_STATUS_UPDATED_NEED_REBOOT) break ;;
        UPDATE_STATUS_IDLE|UPDATE_STATUS_REPORTING_ERROR_EVENT)
            # IDLE within the first minute may just be the async check not
            # having started yet; after that it means the attempt ended.
            if [ $(( $(date +%s) - START )) -gt 60 ]; then
                echo "update did not proceed; update_engine log follows" >&2
                vm_ssh 'tail -60 /var/log/update_engine.log' >&2 || true
                exit 1
            fi ;;
    esac
    [ "$(date +%s)" -lt "$DEADLINE" ] || { echo "timed out waiting for the update" >&2; exit 1; }
    sleep 15
done
echo "OK   update applied to the inactive slot"

if vm_ssh 'grep -q "Waiving payload signature checks" /var/log/update_engine.log' 2>/dev/null; then
    echo "FAIL: signature checks were waived -- this was not an official-mode update" >&2
    exit 1
fi
echo "OK   payload signature checks were not waived (verified against the baked pubkey)"

echo "-- GPT slot state after postinstall (KERN-B must now win)"
vm_ssh 'cgpt show -i 2 /dev/sdb; cgpt show -i 4 /dev/sdb' | sed 's/^/    /'
PRIO_A="$(vm_ssh 'cgpt show -i 2 -P /dev/sdb')"
PRIO_B="$(vm_ssh 'cgpt show -i 4 -P /dev/sdb')"
echo "    KERN-A priority=$PRIO_A KERN-B priority=$PRIO_B"
[ "$PRIO_B" -gt "$PRIO_A" ] || { echo "FAIL: KERN-B does not have boot priority" >&2; exit 1; }

echo "-- rebooting into the new slot (ROOT-B, new release kernel)"
vm_ssh 'reboot' 2>/dev/null || true
wait_stopped

# The new rootfs is a release rootfs: no SSH. Verify from the outside.
echo "-- offline check: ROOT-B contents"
OFF=$(( $(sfdisk -J "$TARGET" | python3 -c '
import json,sys
d=json.load(sys.stdin)
print([p["start"] for p in d["partitiontable"]["partitions"] if p["node"].endswith("5")][0])') * 512 ))
NEWLSB="$(debugfs -c -R 'cat /etc/lsb-release' "$TARGET?offset=$OFF" 2>/dev/null)"
echo "$NEWLSB" | sed 's/^/    /'
echo "$NEWLSB" | grep -q "CHROMEOS_RELEASE_VERSION=${EXPECT}" || {
    echo "FAIL: ROOT-B does not contain ${EXPECT}" >&2; exit 1
}
echo "OK   ROOT-B carries CHROMEOS_RELEASE_VERSION=${EXPECT}"

vm_boot CROS_VM_BOOT_DISK2=1 CROS_VM_OFFICIAL=1 CROS_VM_ROOT_PART=5 \
        CROS_VM_KERNEL="$NEW_KERNEL"
echo "   waiting 180s for the new slot to boot and mark itself good..."
sleep 180
docker kill "cros-vm-$ID" >/dev/null 2>&1 || true
wait_stopped

# chromeos-setgoodkernel runs once system-services started on the NEW
# slot: KERN-B successful=1 is proof the updated system booted.
SUCC_B="$(run_sdk cgpt show -i 4 -S "$TARGET_SDK" | tr -d '[:space:]')"
TRIES_B="$(run_sdk cgpt show -i 4 -T "$TARGET_SDK" | tr -d '[:space:]')"
echo "    KERN-B successful=$SUCC_B tries=$TRIES_B"
if [ "$SUCC_B" = 1 ]; then
    echo
    echo "=== UPDATE VERIFIED: ${BASE_VER} -> ${EXPECT} from ${OMAHA}, applied to ROOT-B,"
    echo "=== slot switched by postinstall, and the updated system booted and marked itself good."
    exit 0
fi
echo "=== KERN-B not marked successful; check $WORK/console.log ===" >&2
exit 1
